language: python
install:
  - pip install tox
  - pip install -e .
matrix:
  include:
    - python: 3.8
      env:
        - TOX_ENV=py38
    - python: 3.9
      env:
        - TOX_ENV=py39
script: tox -e $TOX_ENV
